image:
  name: sagemath/sagemath:latest
  entrypoint: [ "" ]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

test:
  tags:
    - shared-fi
  before_script:
    - sage --pip3 install Ptable
  script:
    - export PATH=$PATH:`sage -c "import sys; import os; print(os.path.join([x for x in sys.path if 'src/bin' in x][0],'../../local/bin') + ':' + \":\".join(sys.path))" 2>/dev/null`
    - sage --python3 setup.py install
    - sage --python3 -m unittest discover curve_analyzer/unit_tests
